Update yamlparser.js
/home/lendodd/NOg/node_modules/ua-parser/node_modules/yamlparser/yamlparser.js:412
            if(m = lines[i].match(r)) {
                            ^
TypeError: Object function each(iterator, context) {
    var index = 0;
    try {
      this._each(function(value) {
        iterator.call(context, value, index++);
      });
    } catch (e) {
      if (e != $break) throw e;
    }
    return this;
  } has no method 'match'
    at preProcess (/home/lendodd/NOg/node_modules/ua-parser/node_modules/yamlparser/yamlparser.js:412:29)
    at Object.eval (/home/lendodd/NOg/node_modules/ua-parser/node_modules/yamlparser/yamlparser.js:434:19)
    at Object.<anonymous> (/home/lendodd/NOg/node_modules/ua-parser/js/index.js:7:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/lendodd/NOg/routes/middleware.js:14:13)